// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"404":{"id":"404","path":"*","parentId":"DocLayout"},"dumi-context-layout":{"id":"dumi-context-layout","path":"/","isLayout":true},"DocLayout":{"id":"DocLayout","path":"/","parentId":"dumi-context-layout","isLayout":true},"docs/index":{"path":"","id":"docs/index","parentId":"DocLayout"},"components/Descriptions/index":{"id":"components/Descriptions/index","path":"components/descriptions","parentId":"DocLayout","meta":{"_atom_route":true}},"components/Form/index":{"id":"components/Form/index","path":"components/form","parentId":"DocLayout","meta":{"_atom_route":true}},"components/QueryTable/index":{"id":"components/QueryTable/index","path":"components/query-table","parentId":"DocLayout","meta":{"_atom_route":true}},"components/Select/index":{"id":"components/Select/index","path":"components/select","parentId":"DocLayout","meta":{"_atom_route":true}},"demo-render":{"id":"demo-render","path":"~demos/:id","parentId":"dumi-context-layout"}} as const;
  return {
    routes,
    routeComponents: {
'404': React.lazy(() => import(/* webpackChunkName: "nm__dumi__dist__client__pages__404" */'/Users/lyralei/Desktop/repository/mine/proComponents/node_modules/.pnpm/dumi@2.4.17_@babel+core@7.26.0_@swc+helpers@0.5.1_@types+node@22.10.5_@types+react@18.3.18_es_5c65bjnyv7tmmij44wt7otndqm/node_modules/dumi/dist/client/pages/404.js')),
'dumi-context-layout': React.lazy(() => import(/* webpackChunkName: "dumi__tmp__dumi__theme__ContextWrapper" */'/Users/lyralei/Desktop/repository/mine/proComponents/.dumi/tmp/dumi/theme/ContextWrapper')),
'DocLayout': React.lazy(() => import(/* webpackChunkName: "nm__dumi__theme-default__layouts__DocLayout__index" */'/Users/lyralei/Desktop/repository/mine/proComponents/node_modules/.pnpm/dumi@2.4.17_@babel+core@7.26.0_@swc+helpers@0.5.1_@types+node@22.10.5_@types+react@18.3.18_es_5c65bjnyv7tmmij44wt7otndqm/node_modules/dumi/theme-default/layouts/DocLayout/index.js')),
'docs/index': React.lazy(() => import(/* webpackChunkName: "docs__index.md" */'/Users/lyralei/Desktop/repository/mine/proComponents/docs/index.md')),
'components/Descriptions/index': React.lazy(() => import(/* webpackChunkName: "Descriptions__index.md" */'/Users/lyralei/Desktop/repository/mine/proComponents/src/Descriptions/index.md')),
'components/Form/index': React.lazy(() => import(/* webpackChunkName: "Form__index.md" */'/Users/lyralei/Desktop/repository/mine/proComponents/src/Form/index.md')),
'components/QueryTable/index': React.lazy(() => import(/* webpackChunkName: "QueryTable__index.md" */'/Users/lyralei/Desktop/repository/mine/proComponents/src/QueryTable/index.md')),
'components/Select/index': React.lazy(() => import(/* webpackChunkName: "Select__index.md" */'/Users/lyralei/Desktop/repository/mine/proComponents/src/Select/index.md')),
'demo-render': React.lazy(() => import(/* webpackChunkName: "nm__dumi__dist__client__pages__Demo__index" */'/Users/lyralei/Desktop/repository/mine/proComponents/node_modules/.pnpm/dumi@2.4.17_@babel+core@7.26.0_@swc+helpers@0.5.1_@types+node@22.10.5_@types+react@18.3.18_es_5c65bjnyv7tmmij44wt7otndqm/node_modules/dumi/dist/client/pages/Demo/index.js')),
},
  };
}
