// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from '/Users/lyralei/Desktop/repository/mine/proComponents/node_modules/.pnpm/dumi@2.4.17_@babel+core@7.26.0_@swc+helpers@0.5.1_@types+node@22.10.5_@types+react@18.3.18_es_5c65bjnyv7tmmij44wt7otndqm/node_modules/dumi/theme-default/slots/NavbarExtra/index.js';
