// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import { frontmatter as fm0, toc as t0 } from '/Users/lyralei/Desktop/repository/mine/proComponents/docs/index.md?type=frontmatter';
import { demoIndex as dmi0 } from '/Users/lyralei/Desktop/repository/mine/proComponents/docs/index.md?type=demo-index';
import { frontmatter as fm1, toc as t1 } from '/Users/lyralei/Desktop/repository/mine/proComponents/src/Form/index.md?type=frontmatter';
import { demoIndex as dmi1 } from '/Users/lyralei/Desktop/repository/mine/proComponents/src/Form/index.md?type=demo-index';
import { frontmatter as fm2, toc as t2 } from '/Users/lyralei/Desktop/repository/mine/proComponents/src/QueryTable/index.md?type=frontmatter';
import { demoIndex as dmi2 } from '/Users/lyralei/Desktop/repository/mine/proComponents/src/QueryTable/index.md?type=demo-index';
import { frontmatter as fm3, toc as t3 } from '/Users/lyralei/Desktop/repository/mine/proComponents/src/Select/index.md?type=frontmatter';
import { demoIndex as dmi3 } from '/Users/lyralei/Desktop/repository/mine/proComponents/src/Select/index.md?type=demo-index';

export const filesMeta = {
  'docs/index': {
    frontmatter: fm0,
    toc: t0,
    demoIndex: dmi0,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/lyralei/Desktop/repository/mine/proComponents/docs/index.md?type=text'),
  },
  'components/Form/index': {
    frontmatter: fm1,
    toc: t1,
    demoIndex: dmi1,
    textGetter: () => import(/* webpackChunkName: "meta__Form" */'/Users/lyralei/Desktop/repository/mine/proComponents/src/Form/index.md?type=text'),
  },
  'components/QueryTable/index': {
    frontmatter: fm2,
    toc: t2,
    demoIndex: dmi2,
    textGetter: () => import(/* webpackChunkName: "meta__QueryTable" */'/Users/lyralei/Desktop/repository/mine/proComponents/src/QueryTable/index.md?type=text'),
  },
  'components/Select/index': {
    frontmatter: fm3,
    toc: t3,
    demoIndex: dmi3,
    textGetter: () => import(/* webpackChunkName: "meta__Select" */'/Users/lyralei/Desktop/repository/mine/proComponents/src/Select/index.md?type=text'),
  },
}

export { tabs as tabsMeta } from './tabs';
